// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CmdOperation/TestProto.proto

package com.bear.demo.protobuff.tryself5.handle;

public final class TestProto {
  private TestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MyMsgReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.gzyouai.hummingbird.engine.tryself5.MyMsgReq}
   */
  public static final class MyMsgReq extends
      com.google.protobuf.GeneratedMessage
      implements MyMsgReqOrBuilder {
    // Use MyMsgReq.newBuilder() to construct.
    private MyMsgReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MyMsgReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MyMsgReq defaultInstance;
    public static MyMsgReq getDefaultInstance() {
      return defaultInstance;
    }

    public MyMsgReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MyMsgReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq.class, com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq.Builder.class);
    }

    public static com.google.protobuf.Parser<MyMsgReq> PARSER =
        new com.google.protobuf.AbstractParser<MyMsgReq>() {
      public MyMsgReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMsgReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MyMsgReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gzyouai.hummingbird.engine.tryself5.MyMsgReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq.class, com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq.Builder.class);
      }

      // Construct using com.gzyouai.hummingbird.engine.tryself5.TestProto.MyMsgReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgReq_descriptor;
      }

      public com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq getDefaultInstanceForType() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq.getDefaultInstance();
      }

      public com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq build() {
        com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq buildPartial() {
        com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq result = new com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq) {
          return mergeFrom((com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq other) {
        if (other == com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.gzyouai.hummingbird.engine.tryself5.MyMsgReq)
    }

    static {
      defaultInstance = new MyMsgReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.gzyouai.hummingbird.engine.tryself5.MyMsgReq)
  }

  public interface MyMsgRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string content = 2;
    /**
     * <code>optional string content = 2;</code>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 2;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code com.gzyouai.hummingbird.engine.tryself5.MyMsgRsp}
   */
  public static final class MyMsgRsp extends
      com.google.protobuf.GeneratedMessage
      implements MyMsgRspOrBuilder {
    // Use MyMsgRsp.newBuilder() to construct.
    private MyMsgRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MyMsgRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MyMsgRsp defaultInstance;
    public static MyMsgRsp getDefaultInstance() {
      return defaultInstance;
    }

    public MyMsgRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MyMsgRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp.class, com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<MyMsgRsp> PARSER =
        new com.google.protobuf.AbstractParser<MyMsgRsp>() {
      public MyMsgRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMsgRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MyMsgRsp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private java.lang.Object content_;
    /**
     * <code>optional string content = 2;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string content = 2;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      name_ = "";
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gzyouai.hummingbird.engine.tryself5.MyMsgRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp.class, com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp.Builder.class);
      }

      // Construct using com.gzyouai.hummingbird.engine.tryself5.TestProto.MyMsgRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgRsp_descriptor;
      }

      public com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp getDefaultInstanceForType() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp.getDefaultInstance();
      }

      public com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp build() {
        com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp buildPartial() {
        com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp result = new com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp) {
          return mergeFrom((com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp other) {
        if (other == com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000002;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.MyMsgRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string content = 2;
      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 2;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.gzyouai.hummingbird.engine.tryself5.MyMsgRsp)
    }

    static {
      defaultInstance = new MyMsgRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.gzyouai.hummingbird.engine.tryself5.MyMsgRsp)
  }

  public interface WalkReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 stepLength = 1;
    /**
     * <code>required int32 stepLength = 1;</code>
     */
    boolean hasStepLength();
    /**
     * <code>required int32 stepLength = 1;</code>
     */
    int getStepLength();

    // required int32 stepNumber = 2;
    /**
     * <code>required int32 stepNumber = 2;</code>
     */
    boolean hasStepNumber();
    /**
     * <code>required int32 stepNumber = 2;</code>
     */
    int getStepNumber();
  }
  /**
   * Protobuf type {@code com.gzyouai.hummingbird.engine.tryself5.WalkReq}
   */
  public static final class WalkReq extends
      com.google.protobuf.GeneratedMessage
      implements WalkReqOrBuilder {
    // Use WalkReq.newBuilder() to construct.
    private WalkReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WalkReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WalkReq defaultInstance;
    public static WalkReq getDefaultInstance() {
      return defaultInstance;
    }

    public WalkReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WalkReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              stepLength_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              stepNumber_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq.class, com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq.Builder.class);
    }

    public static com.google.protobuf.Parser<WalkReq> PARSER =
        new com.google.protobuf.AbstractParser<WalkReq>() {
      public WalkReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WalkReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WalkReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 stepLength = 1;
    public static final int STEPLENGTH_FIELD_NUMBER = 1;
    private int stepLength_;
    /**
     * <code>required int32 stepLength = 1;</code>
     */
    public boolean hasStepLength() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 stepLength = 1;</code>
     */
    public int getStepLength() {
      return stepLength_;
    }

    // required int32 stepNumber = 2;
    public static final int STEPNUMBER_FIELD_NUMBER = 2;
    private int stepNumber_;
    /**
     * <code>required int32 stepNumber = 2;</code>
     */
    public boolean hasStepNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 stepNumber = 2;</code>
     */
    public int getStepNumber() {
      return stepNumber_;
    }

    private void initFields() {
      stepLength_ = 0;
      stepNumber_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStepLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStepNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, stepLength_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, stepNumber_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, stepLength_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, stepNumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gzyouai.hummingbird.engine.tryself5.WalkReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq.class, com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq.Builder.class);
      }

      // Construct using com.gzyouai.hummingbird.engine.tryself5.TestProto.WalkReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stepLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        stepNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkReq_descriptor;
      }

      public com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq getDefaultInstanceForType() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq.getDefaultInstance();
      }

      public com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq build() {
        com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq buildPartial() {
        com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq result = new com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stepLength_ = stepLength_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.stepNumber_ = stepNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq) {
          return mergeFrom((com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq other) {
        if (other == com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq.getDefaultInstance()) return this;
        if (other.hasStepLength()) {
          setStepLength(other.getStepLength());
        }
        if (other.hasStepNumber()) {
          setStepNumber(other.getStepNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStepLength()) {
          
          return false;
        }
        if (!hasStepNumber()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 stepLength = 1;
      private int stepLength_ ;
      /**
       * <code>required int32 stepLength = 1;</code>
       */
      public boolean hasStepLength() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 stepLength = 1;</code>
       */
      public int getStepLength() {
        return stepLength_;
      }
      /**
       * <code>required int32 stepLength = 1;</code>
       */
      public Builder setStepLength(int value) {
        bitField0_ |= 0x00000001;
        stepLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 stepLength = 1;</code>
       */
      public Builder clearStepLength() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stepLength_ = 0;
        onChanged();
        return this;
      }

      // required int32 stepNumber = 2;
      private int stepNumber_ ;
      /**
       * <code>required int32 stepNumber = 2;</code>
       */
      public boolean hasStepNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 stepNumber = 2;</code>
       */
      public int getStepNumber() {
        return stepNumber_;
      }
      /**
       * <code>required int32 stepNumber = 2;</code>
       */
      public Builder setStepNumber(int value) {
        bitField0_ |= 0x00000002;
        stepNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 stepNumber = 2;</code>
       */
      public Builder clearStepNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stepNumber_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.gzyouai.hummingbird.engine.tryself5.WalkReq)
    }

    static {
      defaultInstance = new WalkReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.gzyouai.hummingbird.engine.tryself5.WalkReq)
  }

  public interface WalkRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool isSucc = 1;
    /**
     * <code>required bool isSucc = 1;</code>
     */
    boolean hasIsSucc();
    /**
     * <code>required bool isSucc = 1;</code>
     */
    boolean getIsSucc();
  }
  /**
   * Protobuf type {@code com.gzyouai.hummingbird.engine.tryself5.WalkRsp}
   */
  public static final class WalkRsp extends
      com.google.protobuf.GeneratedMessage
      implements WalkRspOrBuilder {
    // Use WalkRsp.newBuilder() to construct.
    private WalkRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WalkRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WalkRsp defaultInstance;
    public static WalkRsp getDefaultInstance() {
      return defaultInstance;
    }

    public WalkRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WalkRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isSucc_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp.class, com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<WalkRsp> PARSER =
        new com.google.protobuf.AbstractParser<WalkRsp>() {
      public WalkRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WalkRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WalkRsp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool isSucc = 1;
    public static final int ISSUCC_FIELD_NUMBER = 1;
    private boolean isSucc_;
    /**
     * <code>required bool isSucc = 1;</code>
     */
    public boolean hasIsSucc() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool isSucc = 1;</code>
     */
    public boolean getIsSucc() {
      return isSucc_;
    }

    private void initFields() {
      isSucc_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIsSucc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isSucc_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSucc_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gzyouai.hummingbird.engine.tryself5.WalkRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp.class, com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp.Builder.class);
      }

      // Construct using com.gzyouai.hummingbird.engine.tryself5.TestProto.WalkRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isSucc_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkRsp_descriptor;
      }

      public com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp getDefaultInstanceForType() {
        return com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp.getDefaultInstance();
      }

      public com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp build() {
        com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp buildPartial() {
        com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp result = new com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isSucc_ = isSucc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp) {
          return mergeFrom((com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp other) {
        if (other == com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp.getDefaultInstance()) return this;
        if (other.hasIsSucc()) {
          setIsSucc(other.getIsSucc());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsSucc()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gzyouai.hummingbird.engine.tryself5.handle.TestProto.WalkRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool isSucc = 1;
      private boolean isSucc_ ;
      /**
       * <code>required bool isSucc = 1;</code>
       */
      public boolean hasIsSucc() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool isSucc = 1;</code>
       */
      public boolean getIsSucc() {
        return isSucc_;
      }
      /**
       * <code>required bool isSucc = 1;</code>
       */
      public Builder setIsSucc(boolean value) {
        bitField0_ |= 0x00000001;
        isSucc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isSucc = 1;</code>
       */
      public Builder clearIsSucc() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSucc_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.gzyouai.hummingbird.engine.tryself5.WalkRsp)
    }

    static {
      defaultInstance = new WalkRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.gzyouai.hummingbird.engine.tryself5.WalkRsp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgRsp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034CmdOperation/TestProto.proto\022\'com.gzyo" +
      "uai.hummingbird.engine.tryself5\"$\n\010MyMsg" +
      "Req\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \001(\t\")\n\010MyMsgRs" +
      "p\022\014\n\004name\030\001 \002(\t\022\017\n\007content\030\002 \001(\t\"1\n\007Walk" +
      "Req\022\022\n\nstepLength\030\001 \002(\005\022\022\n\nstepNumber\030\002 " +
      "\002(\005\"\031\n\007WalkRsp\022\016\n\006isSucc\030\001 \002(\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgReq_descriptor,
              new java.lang.String[] { "Id", "Name", });
          internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgRsp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_gzyouai_hummingbird_engine_tryself5_MyMsgRsp_descriptor,
              new java.lang.String[] { "Name", "Content", });
          internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkReq_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkReq_descriptor,
              new java.lang.String[] { "StepLength", "StepNumber", });
          internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkRsp_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_gzyouai_hummingbird_engine_tryself5_WalkRsp_descriptor,
              new java.lang.String[] { "IsSucc", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
