// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CmdBox.proto

package com.bear.demo.nettyDemo;

public final class CmdBox {
  private CmdBox() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CmdOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.bear.demo.nettyDemo.Message message = 1;
    /**
     * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
     */
    com.bear.demo.nettyDemo.CmdBox.Message getMessage();
    /**
     * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
     */
    com.bear.demo.nettyDemo.CmdBox.MessageOrBuilder getMessageOrBuilder();

    // optional bytes childMessage = 2;
    /**
     * <code>optional bytes childMessage = 2;</code>
     */
    boolean hasChildMessage();
    /**
     * <code>optional bytes childMessage = 2;</code>
     */
    com.google.protobuf.ByteString getChildMessage();

    // optional sint32 appendCode = 3;
    /**
     * <code>optional sint32 appendCode = 3;</code>
     */
    boolean hasAppendCode();
    /**
     * <code>optional sint32 appendCode = 3;</code>
     */
    int getAppendCode();

    // optional bytes appendData = 4;
    /**
     * <code>optional bytes appendData = 4;</code>
     */
    boolean hasAppendData();
    /**
     * <code>optional bytes appendData = 4;</code>
     */
    com.google.protobuf.ByteString getAppendData();

    // optional bool compress = 5;
    /**
     * <code>optional bool compress = 5;</code>
     *
     * <pre>
     *data 是否压缩
     * </pre>
     */
    boolean hasCompress();
    /**
     * <code>optional bool compress = 5;</code>
     *
     * <pre>
     *data 是否压缩
     * </pre>
     */
    boolean getCompress();
  }
  /**
   * Protobuf type {@code com.bear.demo.nettyDemo.Cmd}
   */
  public static final class Cmd extends
      com.google.protobuf.GeneratedMessage
      implements CmdOrBuilder {
    // Use Cmd.newBuilder() to construct.
    private Cmd(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Cmd(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Cmd defaultInstance;
    public static Cmd getDefaultInstance() {
      return defaultInstance;
    }

    public Cmd getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Cmd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.bear.demo.nettyDemo.CmdBox.Message.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = message_.toBuilder();
              }
              message_ = input.readMessage(com.bear.demo.nettyDemo.CmdBox.Message.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(message_);
                message_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              childMessage_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              appendCode_ = input.readSInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              appendData_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              compress_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_Cmd_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_Cmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bear.demo.nettyDemo.CmdBox.Cmd.class, com.bear.demo.nettyDemo.CmdBox.Cmd.Builder.class);
    }

    public static com.google.protobuf.Parser<Cmd> PARSER =
        new com.google.protobuf.AbstractParser<Cmd>() {
      public Cmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cmd(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Cmd> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.bear.demo.nettyDemo.Message message = 1;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private com.bear.demo.nettyDemo.CmdBox.Message message_;
    /**
     * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
     */
    public com.bear.demo.nettyDemo.CmdBox.Message getMessage() {
      return message_;
    }
    /**
     * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
     */
    public com.bear.demo.nettyDemo.CmdBox.MessageOrBuilder getMessageOrBuilder() {
      return message_;
    }

    // optional bytes childMessage = 2;
    public static final int CHILDMESSAGE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString childMessage_;
    /**
     * <code>optional bytes childMessage = 2;</code>
     */
    public boolean hasChildMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes childMessage = 2;</code>
     */
    public com.google.protobuf.ByteString getChildMessage() {
      return childMessage_;
    }

    // optional sint32 appendCode = 3;
    public static final int APPENDCODE_FIELD_NUMBER = 3;
    private int appendCode_;
    /**
     * <code>optional sint32 appendCode = 3;</code>
     */
    public boolean hasAppendCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional sint32 appendCode = 3;</code>
     */
    public int getAppendCode() {
      return appendCode_;
    }

    // optional bytes appendData = 4;
    public static final int APPENDDATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString appendData_;
    /**
     * <code>optional bytes appendData = 4;</code>
     */
    public boolean hasAppendData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes appendData = 4;</code>
     */
    public com.google.protobuf.ByteString getAppendData() {
      return appendData_;
    }

    // optional bool compress = 5;
    public static final int COMPRESS_FIELD_NUMBER = 5;
    private boolean compress_;
    /**
     * <code>optional bool compress = 5;</code>
     *
     * <pre>
     *data 是否压缩
     * </pre>
     */
    public boolean hasCompress() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool compress = 5;</code>
     *
     * <pre>
     *data 是否压缩
     * </pre>
     */
    public boolean getCompress() {
      return compress_;
    }

    private void initFields() {
      message_ = com.bear.demo.nettyDemo.CmdBox.Message.getDefaultInstance();
      childMessage_ = com.google.protobuf.ByteString.EMPTY;
      appendCode_ = 0;
      appendData_ = com.google.protobuf.ByteString.EMPTY;
      compress_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMessage().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, message_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, childMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, appendCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, appendData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, compress_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, message_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, childMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, appendCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, appendData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, compress_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bear.demo.nettyDemo.CmdBox.Cmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Cmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Cmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Cmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Cmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Cmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Cmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Cmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Cmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Cmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bear.demo.nettyDemo.CmdBox.Cmd prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bear.demo.nettyDemo.Cmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.bear.demo.nettyDemo.CmdBox.CmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_Cmd_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_Cmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bear.demo.nettyDemo.CmdBox.Cmd.class, com.bear.demo.nettyDemo.CmdBox.Cmd.Builder.class);
      }

      // Construct using com.bear.demo.nettyDemo.CmdBox.Cmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (messageBuilder_ == null) {
          message_ = com.bear.demo.nettyDemo.CmdBox.Message.getDefaultInstance();
        } else {
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        childMessage_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        appendCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        appendData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        compress_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_Cmd_descriptor;
      }

      public com.bear.demo.nettyDemo.CmdBox.Cmd getDefaultInstanceForType() {
        return com.bear.demo.nettyDemo.CmdBox.Cmd.getDefaultInstance();
      }

      public com.bear.demo.nettyDemo.CmdBox.Cmd build() {
        com.bear.demo.nettyDemo.CmdBox.Cmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bear.demo.nettyDemo.CmdBox.Cmd buildPartial() {
        com.bear.demo.nettyDemo.CmdBox.Cmd result = new com.bear.demo.nettyDemo.CmdBox.Cmd(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (messageBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.childMessage_ = childMessage_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.appendCode_ = appendCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.appendData_ = appendData_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.compress_ = compress_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bear.demo.nettyDemo.CmdBox.Cmd) {
          return mergeFrom((com.bear.demo.nettyDemo.CmdBox.Cmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bear.demo.nettyDemo.CmdBox.Cmd other) {
        if (other == com.bear.demo.nettyDemo.CmdBox.Cmd.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        if (other.hasChildMessage()) {
          setChildMessage(other.getChildMessage());
        }
        if (other.hasAppendCode()) {
          setAppendCode(other.getAppendCode());
        }
        if (other.hasAppendData()) {
          setAppendData(other.getAppendData());
        }
        if (other.hasCompress()) {
          setCompress(other.getCompress());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessage()) {
          
          return false;
        }
        if (!getMessage().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bear.demo.nettyDemo.CmdBox.Cmd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bear.demo.nettyDemo.CmdBox.Cmd) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.bear.demo.nettyDemo.Message message = 1;
      private com.bear.demo.nettyDemo.CmdBox.Message message_ = com.bear.demo.nettyDemo.CmdBox.Message.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.bear.demo.nettyDemo.CmdBox.Message, com.bear.demo.nettyDemo.CmdBox.Message.Builder, com.bear.demo.nettyDemo.CmdBox.MessageOrBuilder> messageBuilder_;
      /**
       * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
       */
      public com.bear.demo.nettyDemo.CmdBox.Message getMessage() {
        if (messageBuilder_ == null) {
          return message_;
        } else {
          return messageBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
       */
      public Builder setMessage(com.bear.demo.nettyDemo.CmdBox.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
       */
      public Builder setMessage(
          com.bear.demo.nettyDemo.CmdBox.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
       */
      public Builder mergeMessage(com.bear.demo.nettyDemo.CmdBox.Message value) {
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              message_ != com.bear.demo.nettyDemo.CmdBox.Message.getDefaultInstance()) {
            message_ =
              com.bear.demo.nettyDemo.CmdBox.Message.newBuilder(message_).mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          messageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = com.bear.demo.nettyDemo.CmdBox.Message.getDefaultInstance();
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
       */
      public com.bear.demo.nettyDemo.CmdBox.Message.Builder getMessageBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
       */
      public com.bear.demo.nettyDemo.CmdBox.MessageOrBuilder getMessageOrBuilder() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          return message_;
        }
      }
      /**
       * <code>required .com.bear.demo.nettyDemo.Message message = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.bear.demo.nettyDemo.CmdBox.Message, com.bear.demo.nettyDemo.CmdBox.Message.Builder, com.bear.demo.nettyDemo.CmdBox.MessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.bear.demo.nettyDemo.CmdBox.Message, com.bear.demo.nettyDemo.CmdBox.Message.Builder, com.bear.demo.nettyDemo.CmdBox.MessageOrBuilder>(
                  message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }

      // optional bytes childMessage = 2;
      private com.google.protobuf.ByteString childMessage_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes childMessage = 2;</code>
       */
      public boolean hasChildMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes childMessage = 2;</code>
       */
      public com.google.protobuf.ByteString getChildMessage() {
        return childMessage_;
      }
      /**
       * <code>optional bytes childMessage = 2;</code>
       */
      public Builder setChildMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        childMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes childMessage = 2;</code>
       */
      public Builder clearChildMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        childMessage_ = getDefaultInstance().getChildMessage();
        onChanged();
        return this;
      }

      // optional sint32 appendCode = 3;
      private int appendCode_ ;
      /**
       * <code>optional sint32 appendCode = 3;</code>
       */
      public boolean hasAppendCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional sint32 appendCode = 3;</code>
       */
      public int getAppendCode() {
        return appendCode_;
      }
      /**
       * <code>optional sint32 appendCode = 3;</code>
       */
      public Builder setAppendCode(int value) {
        bitField0_ |= 0x00000004;
        appendCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 appendCode = 3;</code>
       */
      public Builder clearAppendCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        appendCode_ = 0;
        onChanged();
        return this;
      }

      // optional bytes appendData = 4;
      private com.google.protobuf.ByteString appendData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes appendData = 4;</code>
       */
      public boolean hasAppendData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes appendData = 4;</code>
       */
      public com.google.protobuf.ByteString getAppendData() {
        return appendData_;
      }
      /**
       * <code>optional bytes appendData = 4;</code>
       */
      public Builder setAppendData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        appendData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes appendData = 4;</code>
       */
      public Builder clearAppendData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        appendData_ = getDefaultInstance().getAppendData();
        onChanged();
        return this;
      }

      // optional bool compress = 5;
      private boolean compress_ ;
      /**
       * <code>optional bool compress = 5;</code>
       *
       * <pre>
       *data 是否压缩
       * </pre>
       */
      public boolean hasCompress() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool compress = 5;</code>
       *
       * <pre>
       *data 是否压缩
       * </pre>
       */
      public boolean getCompress() {
        return compress_;
      }
      /**
       * <code>optional bool compress = 5;</code>
       *
       * <pre>
       *data 是否压缩
       * </pre>
       */
      public Builder setCompress(boolean value) {
        bitField0_ |= 0x00000010;
        compress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool compress = 5;</code>
       *
       * <pre>
       *data 是否压缩
       * </pre>
       */
      public Builder clearCompress() {
        bitField0_ = (bitField0_ & ~0x00000010);
        compress_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.bear.demo.nettyDemo.Cmd)
    }

    static {
      defaultInstance = new Cmd(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.bear.demo.nettyDemo.Cmd)
  }

  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required sint32 messageId = 1;
    /**
     * <code>required sint32 messageId = 1;</code>
     */
    boolean hasMessageId();
    /**
     * <code>required sint32 messageId = 1;</code>
     */
    int getMessageId();

    // required sint32 serverId = 2;
    /**
     * <code>required sint32 serverId = 2;</code>
     */
    boolean hasServerId();
    /**
     * <code>required sint32 serverId = 2;</code>
     */
    int getServerId();

    // optional sint32 playerId = 3;
    /**
     * <code>optional sint32 playerId = 3;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>optional sint32 playerId = 3;</code>
     */
    int getPlayerId();

    // optional int64 clientTime = 4;
    /**
     * <code>optional int64 clientTime = 4;</code>
     */
    boolean hasClientTime();
    /**
     * <code>optional int64 clientTime = 4;</code>
     */
    long getClientTime();

    // optional int64 serverTime = 5;
    /**
     * <code>optional int64 serverTime = 5;</code>
     */
    boolean hasServerTime();
    /**
     * <code>optional int64 serverTime = 5;</code>
     */
    long getServerTime();
  }
  /**
   * Protobuf type {@code com.bear.demo.nettyDemo.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              messageId_ = input.readSInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              serverId_ = input.readSInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              playerId_ = input.readSInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              clientTime_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              serverTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bear.demo.nettyDemo.CmdBox.Message.class, com.bear.demo.nettyDemo.CmdBox.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required sint32 messageId = 1;
    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <code>required sint32 messageId = 1;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required sint32 messageId = 1;</code>
     */
    public int getMessageId() {
      return messageId_;
    }

    // required sint32 serverId = 2;
    public static final int SERVERID_FIELD_NUMBER = 2;
    private int serverId_;
    /**
     * <code>required sint32 serverId = 2;</code>
     */
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required sint32 serverId = 2;</code>
     */
    public int getServerId() {
      return serverId_;
    }

    // optional sint32 playerId = 3;
    public static final int PLAYERID_FIELD_NUMBER = 3;
    private int playerId_;
    /**
     * <code>optional sint32 playerId = 3;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional sint32 playerId = 3;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    // optional int64 clientTime = 4;
    public static final int CLIENTTIME_FIELD_NUMBER = 4;
    private long clientTime_;
    /**
     * <code>optional int64 clientTime = 4;</code>
     */
    public boolean hasClientTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 clientTime = 4;</code>
     */
    public long getClientTime() {
      return clientTime_;
    }

    // optional int64 serverTime = 5;
    public static final int SERVERTIME_FIELD_NUMBER = 5;
    private long serverTime_;
    /**
     * <code>optional int64 serverTime = 5;</code>
     */
    public boolean hasServerTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 serverTime = 5;</code>
     */
    public long getServerTime() {
      return serverTime_;
    }

    private void initFields() {
      messageId_ = 0;
      serverId_ = 0;
      playerId_ = 0;
      clientTime_ = 0L;
      serverTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt32(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt32(2, serverId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, playerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, clientTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, serverTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, serverId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, playerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, clientTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, serverTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bear.demo.nettyDemo.CmdBox.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bear.demo.nettyDemo.CmdBox.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bear.demo.nettyDemo.CmdBox.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bear.demo.nettyDemo.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.bear.demo.nettyDemo.CmdBox.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bear.demo.nettyDemo.CmdBox.Message.class, com.bear.demo.nettyDemo.CmdBox.Message.Builder.class);
      }

      // Construct using com.bear.demo.nettyDemo.CmdBox.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        clientTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        serverTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_Message_descriptor;
      }

      public com.bear.demo.nettyDemo.CmdBox.Message getDefaultInstanceForType() {
        return com.bear.demo.nettyDemo.CmdBox.Message.getDefaultInstance();
      }

      public com.bear.demo.nettyDemo.CmdBox.Message build() {
        com.bear.demo.nettyDemo.CmdBox.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bear.demo.nettyDemo.CmdBox.Message buildPartial() {
        com.bear.demo.nettyDemo.CmdBox.Message result = new com.bear.demo.nettyDemo.CmdBox.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.clientTime_ = clientTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.serverTime_ = serverTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bear.demo.nettyDemo.CmdBox.Message) {
          return mergeFrom((com.bear.demo.nettyDemo.CmdBox.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bear.demo.nettyDemo.CmdBox.Message other) {
        if (other == com.bear.demo.nettyDemo.CmdBox.Message.getDefaultInstance()) return this;
        if (other.hasMessageId()) {
          setMessageId(other.getMessageId());
        }
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasClientTime()) {
          setClientTime(other.getClientTime());
        }
        if (other.hasServerTime()) {
          setServerTime(other.getServerTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageId()) {
          
          return false;
        }
        if (!hasServerId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bear.demo.nettyDemo.CmdBox.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bear.demo.nettyDemo.CmdBox.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required sint32 messageId = 1;
      private int messageId_ ;
      /**
       * <code>required sint32 messageId = 1;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required sint32 messageId = 1;</code>
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>required sint32 messageId = 1;</code>
       */
      public Builder setMessageId(int value) {
        bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 messageId = 1;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = 0;
        onChanged();
        return this;
      }

      // required sint32 serverId = 2;
      private int serverId_ ;
      /**
       * <code>required sint32 serverId = 2;</code>
       */
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required sint32 serverId = 2;</code>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>required sint32 serverId = 2;</code>
       */
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000002;
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 serverId = 2;</code>
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverId_ = 0;
        onChanged();
        return this;
      }

      // optional sint32 playerId = 3;
      private int playerId_ ;
      /**
       * <code>optional sint32 playerId = 3;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional sint32 playerId = 3;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional sint32 playerId = 3;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000004;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 playerId = 3;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        playerId_ = 0;
        onChanged();
        return this;
      }

      // optional int64 clientTime = 4;
      private long clientTime_ ;
      /**
       * <code>optional int64 clientTime = 4;</code>
       */
      public boolean hasClientTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 clientTime = 4;</code>
       */
      public long getClientTime() {
        return clientTime_;
      }
      /**
       * <code>optional int64 clientTime = 4;</code>
       */
      public Builder setClientTime(long value) {
        bitField0_ |= 0x00000008;
        clientTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 clientTime = 4;</code>
       */
      public Builder clearClientTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        clientTime_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 serverTime = 5;
      private long serverTime_ ;
      /**
       * <code>optional int64 serverTime = 5;</code>
       */
      public boolean hasServerTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 serverTime = 5;</code>
       */
      public long getServerTime() {
        return serverTime_;
      }
      /**
       * <code>optional int64 serverTime = 5;</code>
       */
      public Builder setServerTime(long value) {
        bitField0_ |= 0x00000010;
        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 serverTime = 5;</code>
       */
      public Builder clearServerTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        serverTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.bear.demo.nettyDemo.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.bear.demo.nettyDemo.Message)
  }

  public interface PlayerMoveRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 moveStep = 1;
    /**
     * <code>required uint32 moveStep = 1;</code>
     */
    boolean hasMoveStep();
    /**
     * <code>required uint32 moveStep = 1;</code>
     */
    int getMoveStep();

    // required uint32 moveDirection = 2;
    /**
     * <code>required uint32 moveDirection = 2;</code>
     */
    boolean hasMoveDirection();
    /**
     * <code>required uint32 moveDirection = 2;</code>
     */
    int getMoveDirection();
  }
  /**
   * Protobuf type {@code com.bear.demo.nettyDemo.PlayerMoveRequest}
   */
  public static final class PlayerMoveRequest extends
      com.google.protobuf.GeneratedMessage
      implements PlayerMoveRequestOrBuilder {
    // Use PlayerMoveRequest.newBuilder() to construct.
    private PlayerMoveRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerMoveRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerMoveRequest defaultInstance;
    public static PlayerMoveRequest getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerMoveRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerMoveRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              moveStep_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              moveDirection_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_PlayerMoveRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_PlayerMoveRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest.class, com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerMoveRequest> PARSER =
        new com.google.protobuf.AbstractParser<PlayerMoveRequest>() {
      public PlayerMoveRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerMoveRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerMoveRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 moveStep = 1;
    public static final int MOVESTEP_FIELD_NUMBER = 1;
    private int moveStep_;
    /**
     * <code>required uint32 moveStep = 1;</code>
     */
    public boolean hasMoveStep() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 moveStep = 1;</code>
     */
    public int getMoveStep() {
      return moveStep_;
    }

    // required uint32 moveDirection = 2;
    public static final int MOVEDIRECTION_FIELD_NUMBER = 2;
    private int moveDirection_;
    /**
     * <code>required uint32 moveDirection = 2;</code>
     */
    public boolean hasMoveDirection() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 moveDirection = 2;</code>
     */
    public int getMoveDirection() {
      return moveDirection_;
    }

    private void initFields() {
      moveStep_ = 0;
      moveDirection_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMoveStep()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMoveDirection()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, moveStep_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, moveDirection_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, moveStep_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, moveDirection_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bear.demo.nettyDemo.PlayerMoveRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_PlayerMoveRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_PlayerMoveRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest.class, com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest.Builder.class);
      }

      // Construct using com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        moveStep_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        moveDirection_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_PlayerMoveRequest_descriptor;
      }

      public com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest getDefaultInstanceForType() {
        return com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest.getDefaultInstance();
      }

      public com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest build() {
        com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest buildPartial() {
        com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest result = new com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.moveStep_ = moveStep_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.moveDirection_ = moveDirection_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest) {
          return mergeFrom((com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest other) {
        if (other == com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest.getDefaultInstance()) return this;
        if (other.hasMoveStep()) {
          setMoveStep(other.getMoveStep());
        }
        if (other.hasMoveDirection()) {
          setMoveDirection(other.getMoveDirection());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMoveStep()) {
          
          return false;
        }
        if (!hasMoveDirection()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bear.demo.nettyDemo.CmdBox.PlayerMoveRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 moveStep = 1;
      private int moveStep_ ;
      /**
       * <code>required uint32 moveStep = 1;</code>
       */
      public boolean hasMoveStep() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 moveStep = 1;</code>
       */
      public int getMoveStep() {
        return moveStep_;
      }
      /**
       * <code>required uint32 moveStep = 1;</code>
       */
      public Builder setMoveStep(int value) {
        bitField0_ |= 0x00000001;
        moveStep_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 moveStep = 1;</code>
       */
      public Builder clearMoveStep() {
        bitField0_ = (bitField0_ & ~0x00000001);
        moveStep_ = 0;
        onChanged();
        return this;
      }

      // required uint32 moveDirection = 2;
      private int moveDirection_ ;
      /**
       * <code>required uint32 moveDirection = 2;</code>
       */
      public boolean hasMoveDirection() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 moveDirection = 2;</code>
       */
      public int getMoveDirection() {
        return moveDirection_;
      }
      /**
       * <code>required uint32 moveDirection = 2;</code>
       */
      public Builder setMoveDirection(int value) {
        bitField0_ |= 0x00000002;
        moveDirection_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 moveDirection = 2;</code>
       */
      public Builder clearMoveDirection() {
        bitField0_ = (bitField0_ & ~0x00000002);
        moveDirection_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.bear.demo.nettyDemo.PlayerMoveRequest)
    }

    static {
      defaultInstance = new PlayerMoveRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.bear.demo.nettyDemo.PlayerMoveRequest)
  }

  public interface PlayerMoveResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 x = 1;
    /**
     * <code>required uint32 x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required uint32 x = 1;</code>
     */
    int getX();

    // required uint32 y = 2;
    /**
     * <code>required uint32 y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>required uint32 y = 2;</code>
     */
    int getY();
  }
  /**
   * Protobuf type {@code com.bear.demo.nettyDemo.PlayerMoveResponse}
   */
  public static final class PlayerMoveResponse extends
      com.google.protobuf.GeneratedMessage
      implements PlayerMoveResponseOrBuilder {
    // Use PlayerMoveResponse.newBuilder() to construct.
    private PlayerMoveResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerMoveResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerMoveResponse defaultInstance;
    public static PlayerMoveResponse getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerMoveResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerMoveResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_PlayerMoveResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_PlayerMoveResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse.class, com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerMoveResponse> PARSER =
        new com.google.protobuf.AbstractParser<PlayerMoveResponse>() {
      public PlayerMoveResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerMoveResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerMoveResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>required uint32 x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    // required uint32 y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>required uint32 y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    private void initFields() {
      x_ = 0;
      y_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, y_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bear.demo.nettyDemo.PlayerMoveResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_PlayerMoveResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_PlayerMoveResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse.class, com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse.Builder.class);
      }

      // Construct using com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bear.demo.nettyDemo.CmdBox.internal_static_com_bear_demo_nettyDemo_PlayerMoveResponse_descriptor;
      }

      public com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse getDefaultInstanceForType() {
        return com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse.getDefaultInstance();
      }

      public com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse build() {
        com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse buildPartial() {
        com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse result = new com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse) {
          return mergeFrom((com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse other) {
        if (other == com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bear.demo.nettyDemo.CmdBox.PlayerMoveResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 x = 1;
      private int x_ ;
      /**
       * <code>required uint32 x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required uint32 x = 1;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      // required uint32 y = 2;
      private int y_ ;
      /**
       * <code>required uint32 y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>required uint32 y = 2;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.bear.demo.nettyDemo.PlayerMoveResponse)
    }

    static {
      defaultInstance = new PlayerMoveResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.bear.demo.nettyDemo.PlayerMoveResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bear_demo_nettyDemo_Cmd_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bear_demo_nettyDemo_Cmd_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bear_demo_nettyDemo_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bear_demo_nettyDemo_Message_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bear_demo_nettyDemo_PlayerMoveRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bear_demo_nettyDemo_PlayerMoveRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bear_demo_nettyDemo_PlayerMoveResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bear_demo_nettyDemo_PlayerMoveResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014CmdBox.proto\022\027com.bear.demo.nettyDemo\"" +
      "\210\001\n\003Cmd\0221\n\007message\030\001 \002(\0132 .com.bear.demo" +
      ".nettyDemo.Message\022\024\n\014childMessage\030\002 \001(\014" +
      "\022\022\n\nappendCode\030\003 \001(\021\022\022\n\nappendData\030\004 \001(\014" +
      "\022\020\n\010compress\030\005 \001(\010\"h\n\007Message\022\021\n\tmessage" +
      "Id\030\001 \002(\021\022\020\n\010serverId\030\002 \002(\021\022\020\n\010playerId\030\003" +
      " \001(\021\022\022\n\nclientTime\030\004 \001(\003\022\022\n\nserverTime\030\005" +
      " \001(\003\"<\n\021PlayerMoveRequest\022\020\n\010moveStep\030\001 " +
      "\002(\r\022\025\n\rmoveDirection\030\002 \002(\r\"*\n\022PlayerMove" +
      "Response\022\t\n\001x\030\001 \002(\r\022\t\n\001y\030\002 \002(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_bear_demo_nettyDemo_Cmd_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_bear_demo_nettyDemo_Cmd_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bear_demo_nettyDemo_Cmd_descriptor,
              new java.lang.String[] { "Message", "ChildMessage", "AppendCode", "AppendData", "Compress", });
          internal_static_com_bear_demo_nettyDemo_Message_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_bear_demo_nettyDemo_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bear_demo_nettyDemo_Message_descriptor,
              new java.lang.String[] { "MessageId", "ServerId", "PlayerId", "ClientTime", "ServerTime", });
          internal_static_com_bear_demo_nettyDemo_PlayerMoveRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_bear_demo_nettyDemo_PlayerMoveRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bear_demo_nettyDemo_PlayerMoveRequest_descriptor,
              new java.lang.String[] { "MoveStep", "MoveDirection", });
          internal_static_com_bear_demo_nettyDemo_PlayerMoveResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_bear_demo_nettyDemo_PlayerMoveResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bear_demo_nettyDemo_PlayerMoveResponse_descriptor,
              new java.lang.String[] { "X", "Y", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
